services:
  mongodb:
    image: mongo:6
    container_name: navruzshop-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - navruzshop-network

  redis:
    image: redis:7
    container_name: navruzshop-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - navruzshop-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: navruzshop-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - navruzshop-network

  auth-service:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: navruzshop-auth
    env_file:
      - ./services/auth/.env
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
      - redis
    networks:
      - navruzshop-network

  user-service:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    container_name: navruzshop-user
    env_file:
      - ./services/user/.env
    ports:
      - "4002:4002"
    depends_on:
      - mongodb
    networks:
      - navruzshop-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: navruzshop-api-gateway
    env_file:
      - ./api-gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
      - redis
    networks:
      - navruzshop-network

networks:
  navruzshop-network:
    driver: bridge
